# Created by trellis-cli v1.7.0
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  tijolocwb.com.br:
    site_hosts:
    - canonical: tijolocwb.com.br
      # redirects:
      # - www.tijolocwb.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:dsemblano/tijolocwb.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: true
    xmlrpc:
      enabled: false
